# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmudid', models.CharField(max_length=64)),
                ('jmdevice', models.CharField(default=b'', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GuMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guuid', models.CharField(default=b'', max_length=64)),
                ('guname', models.CharField(max_length=20)),
                ('gupass', models.CharField(max_length=20)),
                ('device', models.CharField(default=b'', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmuid', models.CharField(default=b'', max_length=64)),
                ('jmdevice', models.CharField(default=b'', max_length=64)),
            ],
        ),
    ]
